### PR TITLE
Use manual virtual keyboard policy

### PR DESCRIPTION
**Pull request by vmiliantsei**
Stops mobile virtual keyboard from flickering on each command.

### CODE REVIEW

**Comment by erkyrath** [comment]
This API is Chrome-only (not supported in Firefox or Safari). Taking a look at `visualViewport` instead.

**Comment by erkyrath** [comment]
Gah. What we really want is `interactive-widget=resizes-content` in the meta viewport tag. But that's *also* Chrome-only right now.

**Comment by curiousdannii** [comment]
Feel free to borrow from my implementation: https://github.com/curiousdannii/asyncglk/blob/master/src/glkote/web/metrics.ts

**Comment by erkyrath** [comment]
Thanks, will look. I know I'm repeating a bunch of basic research here... but then a bunch of new solutions are showing up! Slowly!

**Comment by curiousdannii** [comment]
Oh, I wouldn't say this is basic research, more like arcane arts! `interactive-widget=resizes-content` is indeed a great addition, and it will be even better when it's widely supported. Looks like Firefox are working on it. Don't know about Safari.

**Comment by erkyrath** [comment]
Forking off my proposed solution into a separate PR, since it has nothing to do with `virtualkeyboardpolicy`.

Discussion continues at: https://github.com/erkyrath/glkote/pull/76

**Comment by erkyrath** [comment]
The effect of the original PR here was -- I think -- to make the keyboard appear the first time you tap on an input element, and then stick up forever. Or at least prevent it from disappearing when the input element loses focus.

I think this is no longer necessary given the other changes that have gone in this week. It felt like a clumsy tweak anyhow -- I'm not sure if there are side effects to putting an onclick handler on the input element.

**Pull request closed without merging**
