### PR TITLE
Use flexbox for input element instead of calculating width manually

### PR DESCRIPTION
**Pull request by juhana**
The same as https://github.com/erkyrath/quixe/pull/40, now in the right place hopefully

### CODE REVIEW

**Comment by erkyrath** [comment]
The report from IFComp is that this fix caused problems in some games. (Change https://github.com/iftechfoundation/ifcomp/pull/181 was reverted at https://github.com/iftechfoundation/ifcomp/commit/c3eb8b822321d58c962ed11a547fb6fe53bf413a .) 

Comment from chat: 

> The problem is visible when applied to Steph Cherrywell’s game

**Comment by erkyrath** [comment]
Screenshot (1)

Screenshot of problem with long paragraphs.

**Comment by juhana** [comment]
Oops, if flexbox is applied to every line then all spans inside the paragraph (whenever the style changes) act as a flexbox. I've amended the commit so that only the line with the input field is a flexbox.

In theory this would still break if there's a long prompt that doesn't fit on one line and it has different styles inside it, but I don't think that would happen in real life.

**Comment by erkyrath** [comment]
thanks, I will take another look.

**Comment by curiousdannii** [comment]
Okay, this fix looks like it works. Good work Juhana! I'll send this for the IFComp site.

But... I'm not sure I'm happy with the limitation that the line with input can't have multiple styles. That's sure to happen eventually.

I think I've found one solution which should handle that. With `flex-wrap` we can handle multi-line multi-span input paragraphs, with the input taking up the rest of the line. The complication is that we'd have to split up the existing spans by words into their own separate spans in order for `flex-wrap` to work. What do you think of that for a more reliable solution?

**Comment by juhana** [comment]
I'm personally not very enthusiastic about anything that requires a lot of JavaScript setup – might just as well use the old width calculation then. But it can't think of a much better option here. It might be possible to use a contenteditable span instead of an input element, which would also allow the input to wrap to a new line, but that would also need quite a bit of JS to get it right.

**Comment by erkyrath** [comment]
Filling in history: this is the cursor positioning bug discussed at https://intfiction.org/t/quixe-chrome-cursor-position/42413 , which derives from this chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1001438

**Comment by curiousdannii** [comment]
They say they've fixed the bug, so it would be worth checking if this patch is still needed.

**Comment by erkyrath** [comment]
I've just been checking, and I don't think it's needed. (Chrome 80.0.3987.149 on Mac.)

Also, the flexbox solution has problems when the prompt is very long, even if it's a single style span. I added a quick test case to sample-demo-full.html in the glkote repository -- type "longprompt". The current code puts the input line in the right place, but the flexbox code doesn't.

I'm still interested in a pure-CSS solution to this, but I don't think it exists at present. 

So, with all of that, I think this patch adds up to a "not needed". I apologize for the long delay in looking at it.

**Comment by erkyrath** [comment]
Closing (see comment above).

**Pull request closed without merging**
