### PR TITLE
Improve iOS keyboard handling

### PR DESCRIPTION
**Pull request by erkyrath**
Copying earlier notes from https://github.com/erkyrath/glkote/pull/69:

Gah. What we really want is `interactive-widget=resizes-content` in the meta viewport tag. But that's also Chrome-only right now.

When testing solutions here, take a peek at the "Problem Statement" section of https://github.com/bramus/viewport-resize-behavior/blob/main/explainer.md#problem-statement . Note that Android browsers (plus Firefox on iOS) have a different behavior from iOS WebKit. I think the default Android behavior is the one we want, but we can't currently get it on iOS.

Dannii wrote:

> Feel free to borrow from my implementation: https://github.com/curiousdannii/asyncglk/blob/master/src/glkote/web/metrics.ts

### CODE REVIEW

**Comment by erkyrath** [comment]
So this started as a copy of the metrics.ts code, but I wound up rearranging the logic quite a bit.

It's still a `resize` handler for `visualViewport`. But it adjusts *both* the height and the top of the gameport, so that the gameport is pinned directly above the keyboard. In other words, the blank space left by shrinking the gameport is now above it (scrolled offscreen) rather than below it (covered by the keyboard).

(It also tries to account for a fixed margin above and below the gameport. E.g. my [OneColumn][] template.)

[OneColumn]: https://eblong.com/zarf/glulx/quixe/i7-onecol-release/play.html

Why? Because iOS Safari is really insistent about trying to scroll the window to keep the input line visible, even though we are in the process of rearranging things so it will be visible anyhow. When I tried the original "change the gameport height" scheme, Safari would *always* scroll the window up so that half the gameport was offscreen and there was a big white gap below it. In some cases (not clear when), even calling `window.scrollTo(0, 0)` would not fix it -- Safari would outright ignore that if it thought it knew better.

With this "change the gameport height and top" scheme, Safari *sometimes* scrolls the window down to leave a big white gap above. But not always, and only when the input line is near the top (e.g. in the first couple of moves of the game). So this is better.

**Comment by erkyrath** [comment]
Note: this PR is not polished yet. I will try adding a few more `window.scrollTo()` calls in case that helps. Also there's a lot of debug log lines to clean up.

**Comment by erkyrath** [comment]
Oh, the other addition is to scroll the buffer window to the bottom after a resize, if it was already scrolled to the bottom. This requires an annoying amount of logic to track that condition, but the basic idea is simple.

**Comment by curiousdannii** [comment]
> Because iOS Safari is really insistent about trying to scroll the window to keep the input line visible, even though we are in the process of rearranging things so it will be visible anyhow. When I tried the original "change the gameport height" scheme, Safari would always scroll the window up so that half the gameport was offscreen and there was a big white gap below it. In some cases (not clear when), even calling window.scrollTo(0, 0) would not fix it -- Safari would outright ignore that if it thought it knew better.

This has been very annoying. Do you know if the extra space is even represented anywhere in the DOM? From what I remember last time I was looking at it, I couldn't see anywhere in the DOM that had extra space, and yet it was there.

Flipping it so the space is at the top is interesting, I'll have to look at that idea some more.

And good to know the iOS 15.0 workaround isn't needed anymore. I'd assumed it probably wasn't, but hadn't bothered checking the browser stats.

**Comment by erkyrath** [comment]
The extra space is in `window` and `<html>`, but not otherwise in the DOM.

iOS 15.0 came out on 20 Sep 2021; 15.1 was 25 Oct 2021. I'm happy to assume that everybody updated.

**Comment by erkyrath** [comment]
Looks good with one additional `window.scrollTo()` call. Tested on iOS Safari, iOS Chrome, iOS Firefox.

**Pull request merged**
